---
development:
  dialect: postgres
  database: {{ envOr "POSTGRES_DB" "server" }}
  user: {{ envOr "POSTGRES_USER" "postgres" }}
  password: {{ envOr "POSTGRES_PASSWORD" "" }}
  host: {{ envOr "POSTGRES_HOST" "127.0.0.1" }}
  port: {{ envOr "POSTGRES_PORT" "5432" }}
  pool: 5

test:
  dialect: postgres
  database: {{ envOr "POSTGRES_DB" "server" }}_test
  user: {{ envOr "POSTGRES_USER" "postgres" }}
  password: {{ envOr "POSTGRES_PASSWORD" "" }}
  host: {{ envOr "POSTGRES_HOST" "127.0.0.1" }}
  port: {{ envOr "POSTGRES_PORT" "5432" }}
  pool: 5

production:
  dialect: postgres
  database: {{ envOr "POSTGRES_DB" "server" }}_prod
  user: {{ envOr "POSTGRES_USER" "postgres" }}
  password: {{ envOr "POSTGRES_PASSWORD" "" }}
  host: {{ envOr "POSTGRES_HOST" "127.0.0.1" }}
  port: {{ envOr "POSTGRES_PORT" "5432" }}
  pool: 10
...